# These are the platforms where the community can support the project financially.
# GitHub will use this file to display a "Sponsor" button at the top of the repository page.
# Only platforms that are not natively supported by a specific key should be listed under 'custom'.

custom:
  - 'https://donito.me/cafepersians'
  - 'https://paylink.payment4.com/en/cafepersians/a43a45c4-e7b6-42f0-bcf8-8f850cd3b239'
  - 'https://paylink.payment4.com/en/cafepersians/01e9f9b6-590f-44e9-874f-7d5a5a50355d'
  - 'https://www.coffeete.ir/Cafepersians'
  - 'https://hamibash.com/cafepersians'
  - 'https://www.coffeebede.com/cafepersians.io'
